version: '2'
services:
    web:
        build: docker/php5-apache
        #image: silexskeleton_web
        container_name: php5-silex
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
